package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGenerate(t *testing.T) {
	root := t.TempDir()

	writeTestFile(t, root, "go.mod", "module example.com/resettest\n\ngo 1.24\n")
	writeTestFile(t, root, "sample.go", `package sample

import "time"

type score int

type child struct {
	value int
}

func (c *child) Reset() {
	c.value = 0
}

// generate:reset
type sample struct {
	number      int
	text        string
	flag        bool
	score       score
	items       []int
	lookup      map[string]int
	numberPtr   *int
	itemsPtr    *[]int
	child       *child
	childValue  child
	array       [2]int
	pointerArray [2]*int
	createdAt   time.Time
	value       any
}

// generate:reset
type box[T any] struct {
	value T
}

// generate:reset
type importedBox[resetpkg1 any] struct {
	createdAt time.Time
	value resetpkg1
}
`)
	writeTestFile(t, root, "nested/item.go", `package nested

// generate:reset
type item struct {
	value int
}
`)
	writeTestFile(t, root, "sample_test.go", `package sample

import (
	"testing"
	"time"
)

func TestGeneratedReset(t *testing.T) {
	number := 42
	arrayNumber1 := 1
	arrayNumber2 := 2
	items := make([]int, 2, 8)
	childPtr := &child{value: 42}
	createdAt := time.Now()
	value := &sample{
		number: 42,
		text: "text",
		flag: true,
		score: 42,
		items: make([]int, 2, 8),
		lookup: map[string]int{"key": 42},
		numberPtr: &number,
		itemsPtr: &items,
		child: childPtr,
		childValue: child{value: 42},
		array: [2]int{1, 2},
		pointerArray: [2]*int{&arrayNumber1, &arrayNumber2},
		createdAt: createdAt,
		value: "value",
	}

	value.Reset()

	if value.number != 0 || value.text != "" || value.flag || value.score != 0 {
		t.Fatal("primitive fields were not reset")
	}
	if value.items == nil || len(value.items) != 0 || cap(value.items) != 8 {
		t.Fatal("slice backing array was not preserved")
	}
	if value.lookup == nil || len(value.lookup) != 0 {
		t.Fatal("map was not cleared")
	}
	if value.numberPtr != &number || number != 0 {
		t.Fatal("primitive pointer was not reset in place")
	}
	if value.itemsPtr != &items || items == nil || len(items) != 0 || cap(items) != 8 {
		t.Fatal("slice pointer was not reset in place")
	}
	if value.child != childPtr || childPtr.value != 0 || value.childValue.value != 0 {
		t.Fatal("nested Reset method was not called")
	}
	if value.array != [2]int{} || !value.createdAt.IsZero() || value.value != nil {
		t.Fatal("zero-value fields were not reset")
	}
	if value.pointerArray[0] != &arrayNumber1 || value.pointerArray[1] != &arrayNumber2 ||
		arrayNumber1 != 0 || arrayNumber2 != 0 {
		t.Fatal("array pointers were not reset in place")
	}

	boxValue := box[int]{value: 42}
	boxValue.Reset()
	if boxValue.value != 0 {
		t.Fatal("generic field was not reset")
	}

	importedBoxValue := importedBox[int]{createdAt: time.Now(), value: 42}
	importedBoxValue.Reset()
	if !importedBoxValue.createdAt.IsZero() || importedBoxValue.value != 0 {
		t.Fatal("generic field with an imported field was not reset")
	}

	var nilValue *sample
	nilValue.Reset()
}
`)

	require.NoError(t, generate(root))

	generated, err := os.ReadFile(filepath.Join(root, generatedFileName))
	require.NoError(t, err)
	require.Contains(t, string(generated), "Code generated by reset")
	require.Contains(t, string(generated), `"time"`)
	_, err = os.Stat(filepath.Join(root, "nested", generatedFileName))
	require.NoError(t, err)

	command := exec.Command("go", "test", "./...")
	command.Dir = root
	output, err := command.CombinedOutput()
	require.NoError(t, err, string(output))
}

func TestGenerateRemovesStaleFile(t *testing.T) {
	root := t.TempDir()

	writeTestFile(t, root, "go.mod", "module example.com/resettest\n\ngo 1.24\n")
	writeTestFile(t, root, "sample.go", "package sample\n")
	writeTestFile(
		t,
		root,
		generatedFileName,
		"// Code generated by reset; DO NOT EDIT.\n\npackage sample\n",
	)

	require.NoError(t, generate(root))

	_, err := os.Stat(filepath.Join(root, generatedFileName))
	require.ErrorIs(t, err, os.ErrNotExist)
}

func writeTestFile(t *testing.T, root, name, contents string) {
	t.Helper()

	path := filepath.Join(root, filepath.FromSlash(name))
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, os.WriteFile(path, []byte(strings.TrimLeft(contents, "\n")), 0o644))
}
