// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/shortener.proto

package api

import (
	reflect "reflect"
	sync "sync"

	proto "google.golang.org/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLShortenRequest) Reset() {
	*x = URLShortenRequest{}
	mi := &file_api_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenRequest) ProtoMessage() {}

func (x *URLShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenRequest.ProtoReflect.Descriptor instead.
func (*URLShortenRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *URLShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type URLShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLShortenResponse) Reset() {
	*x = URLShortenResponse{}
	mi := &file_api_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenResponse) ProtoMessage() {}

func (x *URLShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenResponse.ProtoReflect.Descriptor instead.
func (*URLShortenResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *URLShortenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type URLExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLExpandRequest) Reset() {
	*x = URLExpandRequest{}
	mi := &file_api_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandRequest) ProtoMessage() {}

func (x *URLExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLExpandRequest.ProtoReflect.Descriptor instead.
func (*URLExpandRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *URLExpandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type URLExpandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLExpandResponse) Reset() {
	*x = URLExpandResponse{}
	mi := &file_api_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandResponse) ProtoMessage() {}

func (x *URLExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLExpandResponse.ProtoReflect.Descriptor instead.
func (*URLExpandResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *URLExpandResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           []*URLData             `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_api_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLsResponse.ProtoReflect.Descriptor instead.
func (*UserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *UserURLsResponse) GetUrl() []*URLData {
	if x != nil {
		return x.Url
	}
	return nil
}

type URLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLData) Reset() {
	*x = URLData{}
	mi := &file_api_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLData) ProtoMessage() {}

func (x *URLData) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLData.ProtoReflect.Descriptor instead.
func (*URLData) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *URLData) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URLData) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_api_shortener_proto protoreflect.FileDescriptor

var file_api_shortener_proto_rawDesc = file_api_shortener_proto_buildRawDesc()

var (
	file_api_shortener_proto_rawDescOnce sync.Once
	file_api_shortener_proto_rawDescData []byte
)

func file_api_shortener_proto_rawDescGZIP() []byte {
	file_api_shortener_proto_rawDescOnce.Do(func() {
		file_api_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_shortener_proto_rawDesc)
	})
	return file_api_shortener_proto_rawDescData
}

var file_api_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_shortener_proto_goTypes = []any{
	(*URLShortenRequest)(nil),  // 0: shortener.URLShortenRequest
	(*URLShortenResponse)(nil), // 1: shortener.URLShortenResponse
	(*URLExpandRequest)(nil),   // 2: shortener.URLExpandRequest
	(*URLExpandResponse)(nil),  // 3: shortener.URLExpandResponse
	(*UserURLsResponse)(nil),   // 4: shortener.UserURLsResponse
	(*URLData)(nil),            // 5: shortener.URLData
	(*emptypb.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_api_shortener_proto_depIdxs = []int32{
	5, // 0: shortener.UserURLsResponse.url:type_name -> shortener.URLData
	0, // 1: shortener.ShortenerService.ShortenURL:input_type -> shortener.URLShortenRequest
	2, // 2: shortener.ShortenerService.ExpandURL:input_type -> shortener.URLExpandRequest
	6, // 3: shortener.ShortenerService.ListUserURLs:input_type -> google.protobuf.Empty
	1, // 4: shortener.ShortenerService.ShortenURL:output_type -> shortener.URLShortenResponse
	3, // 5: shortener.ShortenerService.ExpandURL:output_type -> shortener.URLExpandResponse
	4, // 6: shortener.ShortenerService.ListUserURLs:output_type -> shortener.UserURLsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_shortener_proto_init() }
func file_api_shortener_proto_init() {
	if File_api_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shortener_proto_goTypes,
		DependencyIndexes: file_api_shortener_proto_depIdxs,
		MessageInfos:      file_api_shortener_proto_msgTypes,
	}.Build()
	File_api_shortener_proto = out.File
	file_api_shortener_proto_goTypes = nil
	file_api_shortener_proto_depIdxs = nil
}

func file_api_shortener_proto_buildRawDesc() []byte {
	syntax := "proto3"
	name := "api/shortener.proto"
	pkg := "shortener"
	goPackage := "github.com/Fa1ry7a1l/url-shortener/api;api"
	fd := &descriptorpb.FileDescriptorProto{
		Syntax:     &syntax,
		Name:       &name,
		Package:    &pkg,
		Dependency: []string{"google/protobuf/empty.proto"},
		Options: &descriptorpb.FileOptions{
			GoPackage: &goPackage,
		},
		MessageType: []*descriptorpb.DescriptorProto{
			message("URLShortenRequest",
				field("url", "url", 1, descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL, descriptorpb.FieldDescriptorProto_TYPE_STRING, ""),
			),
			message("URLShortenResponse",
				field("result", "result", 1, descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL, descriptorpb.FieldDescriptorProto_TYPE_STRING, ""),
			),
			message("URLExpandRequest",
				field("id", "id", 1, descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL, descriptorpb.FieldDescriptorProto_TYPE_STRING, ""),
			),
			message("URLExpandResponse",
				field("result", "result", 1, descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL, descriptorpb.FieldDescriptorProto_TYPE_STRING, ""),
			),
			message("UserURLsResponse",
				field("url", "url", 1, descriptorpb.FieldDescriptorProto_LABEL_REPEATED, descriptorpb.FieldDescriptorProto_TYPE_MESSAGE, ".shortener.URLData"),
			),
			message("URLData",
				field("short_url", "shortUrl", 1, descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL, descriptorpb.FieldDescriptorProto_TYPE_STRING, ""),
				field("original_url", "originalUrl", 2, descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL, descriptorpb.FieldDescriptorProto_TYPE_STRING, ""),
			),
		},
		Service: []*descriptorpb.ServiceDescriptorProto{
			{
				Name: proto.String("ShortenerService"),
				Method: []*descriptorpb.MethodDescriptorProto{
					method("ShortenURL", ".shortener.URLShortenRequest", ".shortener.URLShortenResponse"),
					method("ExpandURL", ".shortener.URLExpandRequest", ".shortener.URLExpandResponse"),
					method("ListUserURLs", ".google.protobuf.Empty", ".shortener.UserURLsResponse"),
				},
			},
		},
	}

	b, err := proto.Marshal(fd)
	if err != nil {
		panic(err)
	}
	return b
}

func message(name string, fields ...*descriptorpb.FieldDescriptorProto) *descriptorpb.DescriptorProto {
	return &descriptorpb.DescriptorProto{
		Name:  proto.String(name),
		Field: fields,
	}
}

func field(
	name string,
	jsonName string,
	number int32,
	label descriptorpb.FieldDescriptorProto_Label,
	kind descriptorpb.FieldDescriptorProto_Type,
	typeName string,
) *descriptorpb.FieldDescriptorProto {
	f := &descriptorpb.FieldDescriptorProto{
		Name:     proto.String(name),
		Number:   proto.Int32(number),
		Label:    label.Enum(),
		Type:     kind.Enum(),
		JsonName: proto.String(jsonName),
	}
	if typeName != "" {
		f.TypeName = proto.String(typeName)
	}
	return f
}

func method(name string, input string, output string) *descriptorpb.MethodDescriptorProto {
	return &descriptorpb.MethodDescriptorProto{
		Name:       proto.String(name),
		InputType:  proto.String(input),
		OutputType: proto.String(output),
	}
}
